sudo: required

services:
  - docker

before_install:
  - docker build -t mdeng123/multi-client -f ./client/Dockerfile.dev ./client

script:
  - echo "no tests"

after_success:
  - docker build -t mdeng123/multi-client ./client
  - docker build -t mdeng123/multi-nginx ./nginx
  - docker build -t mdeng123/multi-server ./server
  - docker build -t mdeng123/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mdeng123/multi-client
  - docker push mdeng123/multi-nginx
  - docker push mdeng123/multi-server
  - docker push mdeng123/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-788744374964
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
